-- CreateEnum
CREATE TYPE "Achievement" AS ENUM ('IsItHype', 'SensorsAreShit');

-- CreateTable
CREATE TABLE "Chat" (
    "telegramId" INT8 NOT NULL,

    CONSTRAINT "Chat_pkey" PRIMARY KEY ("telegramId")
);

-- CreateTable
CREATE TABLE "Tag" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "tag" STRING NOT NULL,
    "chatTelegramId" INT8 NOT NULL,

    CONSTRAINT "Tag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "telegramId" INT8 NOT NULL,
    "displayName" STRING NOT NULL,
    "telegramUsername" STRING,
    "chatTelegramId" INT8 NOT NULL,
    "countersId" INT4,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Counters" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "telegramUserId" INT8 NOT NULL,
    "telegramChatId" INT8 NOT NULL,
    "isItHypeCounter" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "Counters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Achievements" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "telegramUserId" INT8 NOT NULL,
    "telegramChatId" INT8 NOT NULL,
    "achievements" "Achievement"[],

    CONSTRAINT "Achievements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_TagToUser" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Tag_tag_chatTelegramId_key" ON "Tag"("tag", "chatTelegramId");

-- CreateIndex
CREATE UNIQUE INDEX "User_telegramUsername_chatTelegramId_key" ON "User"("telegramUsername", "chatTelegramId");

-- CreateIndex
CREATE UNIQUE INDEX "User_telegramId_chatTelegramId_key" ON "User"("telegramId", "chatTelegramId");

-- CreateIndex
CREATE UNIQUE INDEX "User_displayName_chatTelegramId_key" ON "User"("displayName", "chatTelegramId");

-- CreateIndex
CREATE UNIQUE INDEX "Counters_telegramChatId_telegramUserId_key" ON "Counters"("telegramChatId", "telegramUserId");

-- CreateIndex
CREATE UNIQUE INDEX "_TagToUser_AB_unique" ON "_TagToUser"("A", "B");

-- CreateIndex
CREATE INDEX "_TagToUser_B_index" ON "_TagToUser"("B");

-- AddForeignKey
ALTER TABLE "Tag" ADD CONSTRAINT "Tag_chatTelegramId_fkey" FOREIGN KEY ("chatTelegramId") REFERENCES "Chat"("telegramId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_chatTelegramId_fkey" FOREIGN KEY ("chatTelegramId") REFERENCES "Chat"("telegramId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Counters" ADD CONSTRAINT "Counters_telegramChatId_telegramUserId_fkey" FOREIGN KEY ("telegramChatId", "telegramUserId") REFERENCES "User"("chatTelegramId", "telegramId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Achievements" ADD CONSTRAINT "Achievements_telegramChatId_telegramUserId_fkey" FOREIGN KEY ("telegramChatId", "telegramUserId") REFERENCES "User"("chatTelegramId", "telegramId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TagToUser" ADD CONSTRAINT "_TagToUser_A_fkey" FOREIGN KEY ("A") REFERENCES "Tag"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_TagToUser" ADD CONSTRAINT "_TagToUser_B_fkey" FOREIGN KEY ("B") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
