version: '3.8'

services:
  crdb:
    container_name: crdb
    hostname: crdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=example-single-node --insecure
    ports:
      - "26257:26257"

