name: ci

on: ['push']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Setup node
        with:
          node-version: '16'

      - name: NPM clean install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test

      - name: Format check
        run: npm run format-check

      - name: Type check
        run: npm run type-check

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  image:
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
