name: ci

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.34.2"

      - name: Deno cache
        run: deno cache apps/cheeseplate/main.ts

      - name: Deno check
        run: deno check apps/cheeseplate/main.ts

      - name: Deno fmt
        run: deno fmt --check

      - name: Deno lint
        run: deno lint

      # - name: Deno test
      #   run: deno test

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  image:
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ success() && github.ref == 'refs/heads/next' }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ github.run_number }}
